name: release
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
env:
  REGISTRY: ghcr.io
  ORG_USERNAME: ${{ github.actor }}

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          pull-request-header: 'Bot (:robot:) requested to create a new release on ${{ github.ref_name }}'
